name: Renovate

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: renovatebot/github-action@v46.1.19 # 46.1.15
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: matthewnitschke-wk/renovate_pub_constraintFiltering
